### ISSUE TITLE
Preposiciones 

### ISSUE THREAD

**Issue by 00Asaf00** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-00Asaf00#1]
[PDF](https://drive.google.com/file/d/17LR8zcwmkkKOXDBmh-YpbvT8n4tPp1lY/view?usp=drivesdk)

**Comment by 23620031** [comment]
PORTADA 17/25 (faltó nombre del profesor)
PROCEDIMIENTO 20/25 (faltó objetivo)
FIGURAS 25/25
RESULTADO Y CONCLUCIÓN 22/25 (falta de resultados)
_______________________________________________________________________________
CALIFICACIÓN TOTAL 16.8/20

CALIFICADO POR ISAÍAS Y EQUIPO

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
